---
version: '2.1'
services:
  ucs-exporter:
    build: .
    container_name: ucs_exporter
    ports:
      - 80:80
    environment:
      PROM_UCS_USERNAME: 'foo'
      PROM_UCS_PASSWORD: 'passw0rd'
      PROM_UCS_HOST: 'my-host.example.com'
      PROM_UCS_LISTEN: '0.0.0.0'
    restart: on-failure
